on:
  issues:
    types: 
      - labeled
      - assigned

jobs:
  echo-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event payload
        run: |
          echo "HELLO WORLD"
          printf '%s' "${{ toJson(github.event) }}" 
