on:
  issues:
    types: 
      - labeled
      - assigned

jobs:
  echo-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event payload
        run: |
          echo "${{ toJson(github.event) }}" >> payload.json
          cat payload.json | jq .
